import React from 'react'
import { Pagination } from 'antd'
import Head from 'next/head'
import Header from '../components/Header'
import ApparelHome from '../components/apparelHome'


export default function homePage()
{

    return (
        <div>
            <Head>
              <title>Hype Heads Full Stack App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <p>BAPE</p>
            <ApparelHome/>
            <p>Fear Of God</p>
            <ApparelHome/>
            <p>Gucci</p>
            <ApparelHome/>
            <p>Off-White</p>
            <ApparelHome/>
            <p>Supreme</p>
            <ApparelHome/>
            <p>Vlone</p>
            <ApparelHome/>
            <Pagination defaultCurrent={1} total={5} />
        </div>
    )
}
