import Head from "next/head";
import Link from "next/link";
import { useRouter } from 'next/router';
import React, { useContext } from "react";
import Header from "../components/Header";
import { Store } from "../utils/Store";

export default function CartScreen() {
  const router = useRouter();
  const { state, dispatch } = useContext(Store);
  const {
    cart: { cartItems },
  } = state;
  const removerItemHandler = (item) => {
    dispatch({ type: 'CART_REMOVE_ITEM', payload: item });
  }
  return (
    <><Head>
      <title>Hype Heads Full Stack App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
      <Header />
      <h1 className="mb-4 text-xl">Shopping Cart</h1>
      {
        cartItems.length === 0 ?
          (<div>
            Cart is empty. <Link href="/">Come Kick it</Link>
          </div>) :
          (
            <div className="grid md:grid-cols-4 md:gap-5">
              <div className="overflow-x-auto md:col-span-3">
                <table className="min-w-full">
                  <thead className="border-b">
                    <tr>
                      <th className="px-5 text-left">Item</th>
                      <th className="px-5 text-left">Quantity</th>
                      <th className="px-5 text-left">Price</th>
                      <th className="px-5">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {cartItems.map((item) => (
                      <tr key={item.slug} className="border-b">
                        <td>
                          <Link href={`/product/${item.slug}`}>
                            <a className="flex items-center">
                              <img
                                src={item.thumbnail}
                                alt={item.shoeName}
                                width={50}
                                height={50}
                              ></img>
                              &nbsp;
                              {item.shoeName}
                            </a>
                          </Link>
                        </td>
                        <td className="p-5 text-left">{item.quantity}</td>
                        <td className="p-5 text-left">{item.retailPrice}</td>
                        <td className="p-5 text-center">
                          <button onClick={() => removerItemHandler(item)}>
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
                              <path strokeLinecap="round" strokeLinejoin="round" d="M9.75 9.75l4.5 4.5m0-4.5l-4.5 4.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                            </svg>
                          </button>

                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <div className="card p-5">
                <ul>
                  <li>
                    <div className="pb-3 text-xl">
                      SUBTOTAL ({cartItems.reduce((a, c) => a + c.quantity, 0)})
                      {' '}
                      : $
                      {cartItems.reduce((a, c) => a + c.quantity * c.retailPrice, 0)}
                    </div>
                  </li>
                  <li>
                    <button
                      onClick={() => router.push('/shipping')}
                      className="primary-button w-full">
                      Check Out
                    </button>
                  </li>
                </ul>
              </div>
            </div>
          )
      }
    </>
  )
}
