import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import Slider from '../components/Slider'
import ProductHome from '../components/kicksHome'
import ApparelHome from '../components/apparelHome'

export default function homePage()
{

    return (
        <div>
            <Head>
              <title>Hype Heads Full Stack App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <Slider/>
            <p>Kicks</p>
            <ProductHome/>
            <p>Apparel</p>
            <ApparelHome/>
        </div>
    )
}
