import Head from 'next/head'
import Header from '../components/Header'
import Register from '../components/Register'
import RegistrationForm from '../components/RegistrationForm'
import SidebarAntD from '../components/SidebarAntD'

export default function Home() {
    
    // console.log(Object.keys(customer));
    // console.log(Object.values(customer));
    // const customerKeys = Object.keys(customer);
    // console.log("Keys", customerKeys);

  return (
    <div >
      <Head>
        <title>Hype Heads Full Stack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 

      {/* Header */}

      {/* <Header/> */}

       {/* Registration Form */}
       
      {/* <RegistrationForm/> */}
      {/* <Register/> */}

    {/* Return Customer info */}
    <SidebarAntD/>
    
      
    </div>
  )
}
