import React from 'react'
import Head from 'next/head'
import { Pagination } from 'antd'
import Header from '../components/Header'
import ProductHome from '../components/kicksHome'

export default function homePage()
{

    return (
        
        <div>
            <Head>
              <title>Hype Heads Full Stack App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <p>Air Jordan</p>
            <ProductHome/>
            <p>New Balance</p>
            <ProductHome/>
            <p>Nike</p>
            <ProductHome/>
            <p>Converse</p>
            <ProductHome/>
            <p>UGG</p>
            <ProductHome/>
            <p>Vans</p>
            <ProductHome/>
            <Pagination defaultCurrent={1} total={5} />
            
        </div>
        
        
    )
}
