const data2 = {
    products2: [
        {
            Name: "drew house mascot ss tee burgundy",
      brand: "drew house",
      silhoutte: "drew house mascot",
      make: "drew house mascot",
      colorway: "burgundy",
      retailPrice: "$ 80.00",
      thumbnail: "https://images.stockx.com/images/drew-house-mascot-ss-tee-burgundy.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1663869959",
      releaseDate: "2022-09-22",
        },
        {
            Name: "Patta New Balance Family T-shirt Oil Green",
      brand: "Patta",
      silhoutte: "Patta New Balance Family",
      make: "Patta New Balance Family",
      colorway: "Oil Green",
      retailPrice: "$ 110.00",
      thumbnail: "https://images.stockx.com/images/Patta-New-Balance-Family-T-shirt-Oil-Green.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1664578556",
      releaseDate: "2022-09-30",
        }, 
        {
            Name: "Arc'teryx x Beams Beta Jacket Dimensions",
      brand: "Arc'teryx",
      silhoutte: "Arc'teryx x Beams Beta",
      make: "Arc'teryx x Beams Beta",
      colorway: "Dimensions",
      retailPrice: "$ 415.00",
      thumbnail: "https://images.stockx.com/images/Arcteryx-x-Beams-Beta-Jacket-Dimensions.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1660118749",
      releaseDate: "2022-09-01",
        }, 
        {
            Name: "Gallery Dept. x Lanvin Jogging Pants Multi (Collection 2)",
      brand: "Gallery Dept.",
      silhoutte: "Gallery Dept. x Lanvin Jogging",
      make: "Gallery Dept. x Lanvin Jogging",
      colorway: "Multi (Collection 2)",
      retailPrice: "$ 965.00",
      thumbnail: "https://images.stockx.com/images/Gallery-Dept-x-Lanvin-Jogging-Pants-Multi-Collection-2.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1647620080",
      releaseDate: "2022-03-15",
        },
        {
            Name: "Stone Island 64120 Brushed Cotton Fleece Hoodie Sage",
      brand: "Stone Island",
      silhoutte: "Stone Island 64120 Brushed Cotton Fleece",
      make: "Stone Island 64120 Brushed Cotton Fleece",
      colorway: "Sage",
      retailPrice: "$ 283.00",
      thumbnail: "https://images.stockx.com/images/Stone-Island-64120-Brushed-Cotton-Fleece-Hoodie-Sage.jpg?fit=fill&bg=FFFFFF&w=700&h=500&fm=webp&auto=compress&trim=color&q=90&dpr=2&updated_at=1639596961",
      releaseDate: "2022-09-01",
        },
    ],
};

export default data2;