import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'

export default function homePage()
{

    return (
        <div>
            <Head>
              <title>Hype Heads Full Stack App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header/>
            <SellerReg/>
        </div>
    )
}
