import { useRouter } from 'next/router'
import Link from 'next/link'
import Head from 'next/head'
import Header from '../../components/Header'
import React, { useContext } from 'react'
import data from '../../utils/data';
import { Image } from 'antd'
import { Store } from '../../utils/Store'


export default function ProductScreen() {
  const { state, dispatch } = useContext(Store);
  const {query} = useRouter();
  const { slug } = query;
  const product = data.products.find(x => x.slug === slug);
  if(!product)
  {
    return <div> Product Not Found </div>
  }
  const addToCartHandler = () => {
    const existItem = state.cart.cartItems.find((x) => x.slug === product.slug);
    const quantity = existItem ? existItem.quantity + 1 : 1;
    dispatch({ type: 'CART_ADD_ITEM', payload: { ...product, quantity }});
  }
  return (
    <><Head>
      <title>Hype Heads Full Stack App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
      <div className="py-2">
      <Link href="/KicksPage"><a>Back To Kicks</a>
      </Link>
      </div>
       <div className="grid md:grid-cols-4 md:gap-3">
      <div className="md:col-span-2">
        <Image 
          src={product.thumbnail}
          alt={product.shoeName}
          width={640}
          height={640}
          layout="responsive"></Image>
      </div>
      </div>
      <div>
        <ul>
          <li>
            <h1 className="text-lg">{product.shoeName}</h1>
          </li>
          <li>{product.releaseDate}</li>
          <li>{product.description}</li>
        </ul>
      </div>
      <div className="card p-5">
        <div className="mb-2 flex justify-between">
          <div>{product.retailPrice}
          </div>
          <button className="primary-button w-full" onClick={addToCartHandler}>Add to Cart</button>
        </div>
      </div>
        {/* */}
        </>
  )
}
